server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/shopping?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: example.shopping.entity
  configuration:
    map-underscore-to-camel-case: true
    
jwt:
  secret: shopping-secret-key
  expiration: 86400000  # 24小时
  header: Authorization
  token-prefix: Bearer 

logging:
  level:
    root: INFO
    example.shopping: INFO
    org.springframework.security: ERROR
    org.springframework.web.filter.CorsFilter: ERROR
    org.apache.catalina.core: ERROR
    org.springframework.web: ERROR 